-- Fusion Redstone Configuration
-- Generated by setup.lua

local config = {}

config.me_interface = nil -- Auto-detect

config.check_interval = 5 -- seconds

-- Tier redstone outputs
-- Format: { address = "...", side = N }
-- Sides: bottom=0, top=1, north=2, south=3, west=4, east=5
config.tiers = {
    [0] = nil,
    [1] = { address = "716a5c44-686c-435c-b56d-0a299eb7e3fd", side = 4 }, -- west
    [2] = nil,
    [3] = nil,
    [4] = nil,
    [5] = nil,
    [6] = nil,
    [7] = nil,
    [8] = nil,
}

return config